FROM node:lts-alpine
ARG SSH_KEY=${SSH_KEY}

RUN apk add build-base git

WORKDIR /home/node
ADD ./package.json ./package.json
ADD ./yarn.lock ./yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

COPY ./docker/entrypoint.local.sh ./entrypoint.sh
COPY ./docker/wait-for.sh ./wait-for.sh

EXPOSE 8080

ENTRYPOINT [ "./entrypoint.sh" ]
