export enum DomainErrorCode {
  CONTACT_NOT_REGISTERED = 'CONTACT_NOT_REGISTERED',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  USER_NOT_FOUND_ERROR = 'USER_NOT_FOUND_ERROR',
  USER_PHONE_IN_USE = 'USER_PHONE_IN_USE',
}
