export enum DomainErrorCode {
  AGGREGATE_ALREADY_CREATED_ERROR = 'AGGREGATE_ALREADY_CREATED_ERROR',
  INVALID_DATE_RANGE = 'INVALID_DATE_RANGE',
  SPEAKER_DOES_NOT_EXISTS = 'SPEAKER_DOES_NOT_EXISTS',
}
