export enum Token {
  EVENT_REPOSITORY = 'EVENT_REPOSITORY',
  SPEAKER_REPOSITORY = 'SPEAKER_REPOSITORY',
  TALK_REPOSITORY = 'TALK_REPOSITORY',
  DOMAIN_EVENT_MAPPER = 'DOMAIN_EVENT_MAPPER',
  EVENT_BUS = 'EVENT_BUS',
  CLOCK = 'CLOCK',
  CRYPTO = 'CRYPTO',
  EMAIL_SENDER = 'EMAIL_SENDER',
}
