export const Token = {
  APP: "APP",
  CONTROLLER: "CONTROLLER",
  HONO: "HONO",
  EVENT_REPOSITORY: "EVENT_REPOSITORY",
  SPEAKER_REPOSITORY: "SPEAKER_REPOSITORY",
  TALK_REPOSITORY: "TALK_REPOSITORY",
  DOMAIN_EVENT_MAPPER: "DOMAIN_EVENT_MAPPER",
  EVENT_BUS: "EVENT_BUS",
  CLOCK: "CLOCK",
  CRYPTO: "CRYPTO",
  EMAIL_SENDER: "EMAIL_SENDER",
};

export type Token = (typeof Token)[keyof typeof Token];
